name: build and deploy portfolio

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker compose build
    - name: Docker push
      run: docker push docker.dariusklein.nl/portfolio
    - name: Docker push
      run: docker push docker.dariusklein.nl/portfolio-docs

# Disabled awaiting runner migration
  # publish:
  
  #   needs: build
    
  #   runs-on: self-hosted
    
  #   steps:
  #   - uses: actions/checkout@v3
  #     with:
  #       sparse-checkout: |
  #         docker-compose.yml
  #   - name: copy file
  #     run: mv docker-compose.yml /home/docker/darius/portfolio
  #   - name: Docker login
  #     run: docker login docker.dariusklein.nl -u Darius -p ${{ secrets.DOCKER_PASSWORD }}
  #   - name: Docker pull
  #     run: |
  #       cd /home/docker/darius/portfolio
  #       docker compose pull
  #   - name: Docker run
  #     run: |
  #       cd /home/docker/darius/portfolio
  #       docker compose up -d
