name: build and run backend

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.kleinwizard.nl/portfolio-backend:latest
    - name: Docker login
      run: docker login docker.kleinwizard.nl -u Darius -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Docker push
      run: docker push docker.kleinwizard.nl/portfolio-backend:latest


  publish:

    runs-on: self-hosted
    steps:
    - name: Docker pull
      run: docker pull docker.kleinwizard.nl/portfolio-backend
    - name: Docker run
      run: docker run --rm -d -p 4002:4002 --name portfolioApi docker.kleinwizard.nl/portfolio-backend 
